package gol

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestLoad(t *testing.T) {
	positions := `.#..................
	   ..#.................
	   ###.................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................
	   ....................`

	world, err := NewWorld(20, 20)
	assert.NoError(t, err)
	assert.Equal(t, 20, world.Height())
	assert.Equal(t, 20, world.Width())

	world.Load(strings.NewReader(positions))
	assert.NoError(t, err)
}
